### ISSUE TITLE
I'm also not getting notification when app is killed (means background notification not getting)

### ISSUE THREAD

**Issue by Irfanhaidermomin** [iFr0z/WorkManagerNotification#2]
How can I resolve?

**Comment by iFr0z** [comment]
What device was used for the test? And also what version of the library, operating system of the device? Stacktrace?

**Comment by niraj-prajapati** [comment]
I'm also facing same issue. any update on this?

**Comment by shyam6764** [comment]
I'm also facing same issue on Oneplus 6T device.

**Comment by MuhammadIbrahimSE** [comment]
I am also facing same issue, when app is killed. any update?

**Comment by MuhammadIbrahimSE** [comment]
I am not getting notification on POCO X3, whereas it is working fine on samsung S8.

**Comment by iFr0z** [comment]
#1
